config/routes.rb
Rails.application.routes.draw do

  resources :auctions do
    resources :bids
    resources :publishings, only: :create
    resources :meets_reserve, only: :create
    resources :watches, only: [:create, :destroy]
  end

  resources :sessions do
    delete :destroy, on: :collection
  end

  resources :users do
    resources :bids
    resources :watches, only: [:index]
  end

  root 'auctions#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    can :watch, Auction do |a|
      user != a.user
    end

    cannot :watch, Auction do |a|
      user == a.user
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_many :bids, dependent: :destroy
  has_many :watches, dependent: :destroy
  belongs_to :user

  has_many :watchers, through: :watches, source: :user

  before_create do
    self.current_bid = 1
  end

  include AASM

  aasm whiny_transitions: false do

    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :canceled
    state :reserve_not_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :meet_reserve do
      transitions from: :published, to: :reserve_met
    end

    event :win do
      transitions from: :reserve_met, to: :won
    end

    event :cancel do
      transitions from: [:published, :reserve_met], to: :cancelled
    end

    event :dont_meet_reserve do
      transitions from: :published, to: :reserve_not_met
    end

  end

  def watched_by?(user)
    watches.exists?(user: user)
  end

  def watch_for(user)
    watches.find_by(user: user)
  end

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user

  validate :bid_is_higher_than_current_highest

  def bid_is_higher_than_current_highest
    if auction.current_bid.present? && (self.bid_price <= auction.current_bid)
      errors.add(:bid_price, "Bid price must be higher than current listed price!")
    end
  end

  validate :user_cant_bid_on_their_own_auction

  def user_cant_bid_on_their_own_auction
    if auction.user_id == self.user_id
      errors.add(:bid_price, "You cannot bid on your own auction!")
    end
  end

  after_commit do
    auction.update_attribute(:current_bid, self.bid_price)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy
  has_many :watches, dependent: :destroy
  has_many :watched_auctions, through: :watches, source: :auction

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".titleize
  end

end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :auction

  validates :user_id, uniqueness: {scope: :auction_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, alert: 'Please sign in' unless user_sign_in?
  end

  def user_sign_in?
    session[:user_id].present?
  end
  helper_method :user_sign_in?

  def current_user
    User.find session[:user_id] if user_sign_in?
  end
  helper_method :current_user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @auctions = Auction.order(created_at: :desc)
  end

  def show
    which_auction = params[:id]
    @auction = Auction.find(which_auction)
    @bid = Bid.new
    @bids = Bid.where(auction_id: @auction).order(created_at: :desc)
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :details, :ends_on, :reserve_price)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @auctions = @user.bids
  end

  def create
    @auction = Auction.find params[:auction_id]
    @bid = Bid.new bid_params
    @bid.auction = @auction
    @bid.user = current_user

    if @bid.save
      redirect_to auction_path(params[:auction_id])
    else
      render 'auctions/show'
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:bid_price, :created_at, :auction_id, :user_id)
  end

end

app/controllers/meets_reserve_controller.rb
class MeetsReserveController < ApplicationController
  before_action :authenticate_user!

  def create
    auction = Auction.find params[:auction_id]
    if auction.meet_reserve!
      redirect_to auction, notice: 'Auction has met reserve!'
    end
  end
end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController
  before_action :authenticate_user!

  def create
    auction = Auction.find params[:auction_id]
    if auction.publish!
      redirect_to auction, notice: 'Auction is published!'
    else
      redirect_to auction, notice: "Can't publish auction, already published?"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Signed in successfully'
    else
      flash.now[:alert] = "Wrong credentials"
      render json: params
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed out successfully'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created successfully'
    else
      render :new
    end
  end

  private

  def user_params
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_comfirmation)
  end

end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController

  before_action :authenticate_user!

  def index
    user = User.find(params[:user_id])
    @auctions = user.watched_auctions
    render 'watches/index'
  end

  def create
    auction = Auction.find(params[:auction_id])
    watch = Watch.new(user: current_user, auction: auction)

    if watch.save
      redirect_to auction_path(auction), notice: 'Auction Liked!'
    else
      redirect_to auction_path(auction), alert: watch.errors.full_messages
    end

  end

  def destroy
    watch = Watch.find(params[:id])
    if watch.destroy
      redirect_to auction_path(watch.auction), notice: 'Auction Unliked!'
    else
      redirect_to auction_path(watch.auction), alert: watch.errors.full_messages
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/meets_reserve_helper.rb
module MeetsReserveHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/auctions/index.html.erb
<div class="container">
  <h1>Main Page</h1>

  <% @auctions.each do |auction| %>
    <% if auction.published? == true || auction.reserve_met? == true %>
      <div>
        <h3><%= link_to auction.title, auction_path(auction) %></h3>
        <hr>
      </div>
    <% elsif auction.user_id == current_user.id %>
      <div>
        <h3><%= link_to auction.title, auction_path(auction) %></h3>
        <hr>
      </div>
    <% end %>
  <% end %>
</div>

app/views/auctions/new.html.erb
<div class="container">

  <h1>Create New Auction</h1>

  <%= simple_form_for @auction do |f| %>
    <%= f.input :title %>
    <%= f.input :details, as: :text %>
    <%= f.label :ends_on %>
    <div class='input-group date' id='datetimepicker1'>
      <input name="ends_on" type='text' class="form-control" />
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
    <p>
    <%= f.input :reserve_price, as: :integer %>
    <%= f.button :submit %>
  <% end %>

  <script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
          format: 'DD/MM/YYYY'
        });
    });
  </script>

</div>

app/views/auctions/show.html.erb
<div class="container">

  <div class="row">
    <div class="title-block col-xs-12 col-sm-6">
      <h1><%= @auction.title %></h1>
      <%= @auction.details %>
    </div>
    <div class="price-block col-xs-12 col-sm-6">
      <p>Current Price $<%= @auction.current_bid %></p>
      <% if @auction.current_bid <= @auction.reserve_price %>
          <p>Reserve Price Not Met</p>
      <% else %>
          <p>Reserve Price Has Been Met</p>
          <% @auction.meet_reserve == true %>
      <% end %>

      <% if @auction.may_publish? && current_user.id == @auction.user_id%>
        <%= button_to 'Publish', auction_publishings_path(@auction), method: :post, :class=>"publish-button btn btn-primary" %>
      <% end %>


      <% if user_sign_in? && can?(:watch, @auction) %>
        <% if @auction.watched_by?(current_user)  %>
          <%= link_to fa_icon("eye-slash 2x"), auction_watch_path(@auction, @auction.watch_for(current_user)), method: :delete %>
        <% else %>
          <%= link_to fa_icon("eye 2x"), auction_watches_path(@auction), method: :post %>
        <% end %>
      <% end %>
    </div>
  </div>


    <div class="row col-xs-12">
      <%= simple_form_for [@auction, @bid] do |f| %>
      <%= f.input :bid_price %>
      <%= f.button :submit %>
      <% end %>
    </div>

  <div class="row col-xs-12">
    <h2>Previous Bids</h2>
    <% @auction.bids.order(created_at: :desc).each do |bid| %>
      <div>
        <p>$<%= bid.bid_price %> at <%= bid.created_at.strftime("%b %d %Y") %></p>
        <strong>by <%= User.find(bid.user_id).first_name %> <%= User.find(bid.user_id).last_name %> </strong>
        <hr>
      </div>
    <% end %>
  </div>

</div>

app/views/bids/index.html.erb
<div class="container">
  <h1>Bids placed by <%= @user&.full_name %></h1>

  <ul>
  <% @auctions.each do |a| %>

    <li><%= link_to a.auction.title, "/auctions/#{a.auction.id}" %></li>
  <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.submit 'Sign Up' %>
  <% end %>
</div>

app/views/watches/index.html.erb
<div class="container">
  <h1>Auctions watched by <%= current_user.first_name %> <%= current_user.last_name %></h1>

  <ul>
    <% @auctions.each do |auction| %>
      <li><%= link_to auction.title, auction %></li>
    <% end %>
  </ul>
</div>